### ISSUE TITLE
setup_dev_environment is out of date

### ISSUE THREAD

**Issue by erikdstock** [loomio/loomio_help#6]
Hi! Was investigating loomio as a possible solution for an org I work with and I was unable to get the service running following the setup guide. In particular the [`bootstrap task mentioned in the script`](https://github.com/loomio/loomio_help/blob/master/content/dev_manual/setup_dev_environment.md#run-the-bootstrap-task) seems to have been removed some time ago - I found it in the [repo history](https://github.com/loomio/loomio/blob/9de01b2c42e035c9451380a4cedef7a1010fcfea/lib/tasks/bootstrap.rake) and tried to walk through some of the steps manually (copying database.yml etc) but was ultimately unsuccessful- when running my own `rake db:setup` I failed somewhere in the `default_group_cover.rb` file and decided it would be best to just ask for help.

That said I like what I see and am really excited to try this out & maybe contribute if yall are open to that!

**Comment by napkindrawing** [comment]
Here's the commit where `bootstrap.rake` was deleted: https://github.com/loomio/loomio/commit/37bb961c1dd95f77fc55386210ea36f1bef350dc

**Comment by robguthrie** [comment]
Thanks for letting me know. I've updated the document for you! Keen to hear how you get on. Thanks again!
